#:schema node_modules/wrangler/config-schema.json
name = "mute-dust-c2e7"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "c29eb20320b9420999569b9bc97fad21" }
]

[assets]
directory = "./public"
